/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.wanzenberg.ulf.mymdi.notused;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import static java.lang.System.out;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;

import net.wanzenberg.ulf.mymdi.database.DB_sqlite;

/**
 *
 * @author Ulf
 */
public class PanelMetadataJPanel extends javax.swing.JPanel {

	static String mySQLStatement;
	static String myDatabase;

	/**
	 * Creates new JPanel PAnelMetadata
	 */
	public PanelMetadataJPanel() {
		initComponents();

		System.out.println("PanelMetadataJPanel_a" );

		// Zugriff auf Datenbank(tabelle) mittels DB_sqlite
		// ------------------------------------------------------------------
		myDatabase = "mywork.db";
		mySQLStatement = "SELECT * FROM object_or_source_metadata";
		DB_sqlite aSQLite_access = new DB_sqlite(myDatabase, mySQLStatement);

		/**
		 * TableModel ...
		 * -----------------------------------------------
		 */
		DefaultTableModel tableModelMetadata = new DefaultTableModel(aSQLite_access.data, aSQLite_access.columnNames);
		// out.println("Anzahl Spalten: " + tableModel1.getColumnCount());
		// out.println("Anzahl Zeilen: " + tableModel1.getRowCount());

		/**
		 * jTable ...
		 * -----------------------------------------------
		 */
		JTable tableMetadata = new JTable();
		tableMetadata.setPreferredScrollableViewportSize(tableMetadata.getPreferredSize());

		// getSize
		Dimension dimensionPanelMetadata = this.getSize();
		out.println("jPanel2 Breite: " + dimensionPanelMetadata.width + " tableMetadata Höhe: " + dimensionPanelMetadata.height);
		Dimension dimensionTableMetadata = tableMetadata.getSize();
		out.println("jTable2 Breite: " + dimensionTableMetadata.width + " tableMetadata Höhe: " + dimensionTableMetadata.height);

		// setModel
		tableMetadata.setModel(tableModelMetadata);

		/**
		 * ...
		 * -----------------------------------------------
		 */
		// jTable2.setAutoCreateRowSorter(true);
		//
		//
		// jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		// jTable2.getColumnModel().getColumn(0).setMinWidth(10);
		// jTable2.getColumnModel().getColumn(0).setMaxWidth(10);
		// jTable2.getColumnModel().getColumn(1).setMinWidth(10);
		// jTable2.getColumnModel().getColumn(2).setMinWidth(10);
		// jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
		//
		//
		
		tableMetadata.setSize(100, 100);

		// ... scrollpane
		// -------------------------------------------------------
		JScrollPane scrollPanelMetadata = new JScrollPane();
		// jScrollPane2.getViewport().add(jTable2);
		//scrollPanelMetadata.add(tableMetadata);
		scrollPanelMetadata.setPreferredSize(new Dimension(100, 100));
		scrollPanelMetadata.setBackground(Color.yellow);

		// this.add(jScrollPane2);
		this.add(tableMetadata);
		this.setBorder(BorderFactory.createLineBorder(Color.red));
		System.out.println("PanelMetadataJPanel_e" );

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
